//! Plan the notes-only project copy.
//!
//! Nothing is assembled into an intermediate image. The rewrite produces an
//! ordered list of *pieces* — spans borrowed from the mapped source, the merged
//! note payload, and a few bytes of generated event headers — which the writer
//! streams straight to disk. A whole project therefore costs one pass over the
//! event headers plus one copy of the bytes into the page cache, instead of
//! allocating and filling a second full-size buffer first.

use std::io::{self, Write};

use crate::error::{MergeError, Result};
use crate::expand::MergedNotes;
use crate::flp::*;
use crate::scan::{ArrangementInfo, ScanResult};

#[derive(Clone, Copy)]
enum Piece {
    /// A span copied verbatim from the source file.
    Source { at: usize, len: usize },
    /// Generated bytes held in the plan's scratch buffer.
    Scratch { at: usize, len: usize },
    /// The merged note payload.
    Merged,
}

pub struct OutputPlan<'a> {
    data: &'a [u8],
    merged: &'a [u8],
    scratch: Vec<u8>,
    pieces: Vec<Piece>,
    pub total_size: usize,
}

impl OutputPlan<'_> {
    fn piece_bytes(&self, piece: &Piece) -> &[u8] {
        match *piece {
            Piece::Source { at, len } => &self.data[at..at + len],
            Piece::Scratch { at, len } => &self.scratch[at..at + len],
            Piece::Merged => self.merged,
        }
    }

    /// Stream the planned project to `writer` in order.
    pub fn write_to(&self, writer: &mut impl Write) -> io::Result<()> {
        for piece in &self.pieces {
            writer.write_all(self.piece_bytes(piece))?;
        }
        Ok(())
    }
}

struct PlanBuilder {
    scratch: Vec<u8>,
    pieces: Vec<Piece>,
}

impl PlanBuilder {
    fn source(&mut self, at: usize, len: usize) {
        if len != 0 {
            self.pieces.push(Piece::Source { at, len });
        }
    }

    /// Copy `bytes` into the scratch buffer and reference them.
    fn generated(&mut self, bytes: &[u8]) {
        let at = self.scratch.len();
        self.scratch.extend_from_slice(bytes);
        self.pieces.push(Piece::Scratch {
            at,
            len: bytes.len(),
        });
    }

    /// Reserve a scratch span to be filled in once its value is known.
    fn placeholder(&mut self, len: usize) -> usize {
        let at = self.scratch.len();
        self.scratch.resize(at + len, 0);
        self.pieces.push(Piece::Scratch { at, len });
        at
    }
}

fn replacement_playlist_record(arr: &ArrangementInfo, target_pattern_id: u16) -> Result<Vec<u8>> {
    let Some(template) = &arr.template else {
        return Ok(Vec::new());
    };
    let mut raw = template.clone();
    let pattern_base = read_u16(&raw, 4) as u32;
    let item_index = pattern_base + target_pattern_id as u32;
    if item_index > 0xFFFF {
        return Err(MergeError::format(
            "Target pattern identifier cannot fit in a Playlist record.",
        ));
    }
    if arr.timeline_length > UINT32_MAX {
        return Err(MergeError::format(
            "An arrangement timeline exceeds FL Studio's 32-bit range.",
        ));
    }
    let section_end = arr.section_offset + arr.timeline_length;
    if section_end > INT32_MAX {
        return Err(MergeError::format(
            "A merged arrangement section exceeds the Pattern Clip offset range.",
        ));
    }

    write_u32(&mut raw, 0, 0); // Playlist position
    write_u16(&mut raw, 6, item_index as u16);
    write_u32(&mut raw, 8, arr.timeline_length as u32);
    write_u16(&mut raw, 14, 0); // no clip group
    let flags = read_u16(&raw, 18) & !MUTED_CLIP_FLAG;
    write_u16(&mut raw, 18, flags);
    write_i32(&mut raw, 24, arr.section_offset as i32);
    write_i32(&mut raw, 28, section_end as i32);
    Ok(raw)
}

/// Walk the event stream once and plan the output project.
pub fn rewrite_project<'a>(
    data: &'a [u8],
    scan: &ScanResult,
    merged: &'a MergedNotes,
) -> Result<OutputPlan<'a>> {
    let note_blob_size = merged.bytes.len();
    if note_blob_size as u64 > UINT32_MAX {
        return Err(MergeError::format(
            "Merged note data exceeds the 4 GiB FLdt chunk limit. Split the project first.",
        ));
    }

    let target_pattern = scan.target_pattern_id;
    let replacements: Vec<Vec<u8>> = scan
        .arrangements
        .iter()
        .map(|arr| replacement_playlist_record(arr, target_pattern))
        .collect::<Result<Vec<_>>>()?;

    let mut builder = PlanBuilder {
        scratch: Vec::with_capacity(4096),
        pieces: Vec::with_capacity(64),
    };

    // FLhd and the FLdt marker, then a reserved slot for the FLdt length.
    builder.source(0, scan.data_length_pos);
    let length_slot = builder.placeholder(4);
    let first_data_piece = builder.pieces.len();

    let data_end = scan.data_end;
    let mut cursor = scan.data_offset;
    let mut copy_start = scan.data_offset;
    let mut current_pattern: Option<u16> = None;
    let mut current_arrangement: Option<u16> = None;
    let mut replaced_target_notes = false;

    while cursor < data_end {
        let event = next_event(data, cursor, data_end)?;
        match event.id {
            EV_NEW_PATTERN => current_pattern = Some(read_u16(data, event.data_offset)),
            EV_NEW_ARRANGEMENT => current_arrangement = Some(read_u16(data, event.data_offset)),
            _ => {}
        }

        let rewritten = match event.id {
            EV_PATTERN_NOTES | EV_PATTERN_CONTROLLERS | EV_PLAYLIST => true,
            EV_PATTERN_LENGTH => current_pattern == Some(target_pattern),
            _ => false,
        };
        if !rewritten {
            cursor = event.next;
            continue;
        }

        // Flush the run of untouched events preceding this one as one span.
        builder.source(copy_start, cursor - copy_start);

        match event.id {
            EV_PATTERN_NOTES => {
                if cursor == scan.target_note_event_start {
                    let mut head = Vec::with_capacity(8);
                    head.push(EV_PATTERN_NOTES);
                    push_varint(&mut head, note_blob_size);
                    builder.generated(&head);
                    builder.pieces.push(Piece::Merged);
                    replaced_target_notes = true;
                } else {
                    // Old pattern notes are now redundant. Emptying them is the
                    // main file-size/loading optimization.
                    builder.generated(&[EV_PATTERN_NOTES, 0]);
                }
            }
            EV_PATTERN_CONTROLLERS => {
                // The requested result is notes-only. Pattern event automation
                // would no longer line up after flattening.
                builder.generated(&[EV_PATTERN_CONTROLLERS, 0]);
            }
            EV_PLAYLIST => {
                let replacement = scan
                    .arrangement_index(current_arrangement.unwrap_or(0))
                    .map(|index| replacements[index].as_slice())
                    .unwrap_or(&[]);
                let mut head = Vec::with_capacity(8);
                head.push(EV_PLAYLIST);
                push_varint(&mut head, replacement.len());
                builder.generated(&head);
                builder.generated(replacement);
            }
            EV_PATTERN_LENGTH => {
                // Auto length: FL Studio derives it from the merged notes.
                builder.generated(&[EV_PATTERN_LENGTH, 0, 0, 0, 0]);
            }
            _ => unreachable!(),
        }

        copy_start = event.next;
        cursor = event.next;
    }

    builder.source(copy_start, data_end - copy_start);

    if !replaced_target_notes {
        return Err(MergeError::format(
            "Internal error: target note event was not replaced.",
        ));
    }

    let last_data_piece = builder.pieces.len();

    // Preserve any nonstandard bytes/chunks following FLdt.
    builder.source(scan.suffix_offset, scan.file_size - scan.suffix_offset);

    let PlanBuilder {
        mut scratch,
        pieces,
        ..
    } = builder;

    let piece_len = |piece: &Piece| -> usize {
        match *piece {
            Piece::Source { len, .. } | Piece::Scratch { len, .. } => len,
            Piece::Merged => note_blob_size,
        }
    };
    let new_data_length: usize = pieces[first_data_piece..last_data_piece]
        .iter()
        .map(piece_len)
        .sum();
    if new_data_length as u64 > UINT32_MAX {
        return Err(MergeError::format(
            "The generated FLdt chunk is larger than FLP's 4 GiB length field.",
        ));
    }
    write_u32(&mut scratch, length_slot, new_data_length as u32);

    let total_size: usize = pieces.iter().map(piece_len).sum();
    Ok(OutputPlan {
        data,
        merged: &merged.bytes,
        scratch,
        pieces,
        total_size,
    })
}
